entity Product
MARudnicki/project_06_2012 pull request #5
Opened 2021-06-25 18:14 UTC by D4nielZ4k

2021-06-26 17:07 UTC, ga1robe approved these changes

2021-06-26 18:13 UTC, MARudnicki requested changes

2021-06-26 18:13 UTC, MARudnicki commented on src/main/java/com/kodilla/domain/Product.java
> +    String groupId;
zmienne powinny byc private

2021-06-26 18:13 UTC, MARudnicki commented on src/main/java/com/kodilla/domain/Product.java
> +    }
Moze warto uzyc Lomboka, jak w PR'ze 
https://github.com/MARudnicki/project_06_2012/pull/7

wtedy getter, settery i konstruktory mozna wygenerowac automatycznie

2021-06-26 18:49 UTC, D4nielZ4k commented
Poprawione.

2021-06-27 06:40 UTC, MARudnicki approved these changes

2021-06-27 10:06 UTC, merged