Jdp210602 2
MARudnicki/project_06_2012 pull request #7
Opened 2021-06-26 08:06 UTC by andrzej-t

Dodałem GroupDto i wymagane metody w kontrolerze...
Jak wypatrzycie coś nie tak, to piszcie... Dzięki!

2021-06-26 17:24 UTC, ga1robe approved these changes

2021-06-26 17:24 UTC, D4nielZ4k approved these changes
Its Ok.

2021-06-26 17:59 UTC, jakjur-dev approved these changes
No conflicts with other devs

2021-06-26 18:11 UTC, MARudnicki requested changes

2021-06-26 18:11 UTC, MARudnicki commented on src/main/resources/application.properties
> +
Te nowe linie sa do usuniecia

2021-06-26 18:11 UTC, MARudnicki commented on src/main/resources/application.properties
> +spring.jpa.open-in-view=true
sprawdzilem czym jest ta flaga
https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
naprawdopodobniej nie jest ona potrzebna

2021-06-26 18:11 UTC, MARudnicki commented on build.gradle
> +    annotationProcessor 'org.projectlombok:lombok:1.18.20'
wystarczy
```
compileOnly 'org.projectlombok:lombok'
annotationProcessor 'org.projectlombok:lombok'
```
wersja zostanie wyznaczona przez plugin springboot'owy

2021-06-26 18:48 UTC, D4nielZ4k commented
Poprawione.

2021-06-27 06:37 UTC, MARudnicki approved these changes

2021-06-28 07:35 UTC, merged

2021-06-28 11:23 UTC, andrzej-t commented
Poprawione. Zmergowane.